name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 22 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN_WAKA }}
          SHOW_COMMIT: TRUE
          SHOW_LANGUAGE: FALSE
          SHOW_PROJECTS: FALSE
          SHOW_PROFILE_VIEWS: TRUE
          SHOW_DAYS_OF_WEEK: TRUE
          SHOW_SHORT_INFO: FALSE
          SHOW_TIMEZONE: FALSE
          SHOW_EDITORS: FALSE
          SHOW_LOC_CHART: FALSE
